homeassistant:
  # Name of the location where Home Assistant is running
  name: Jonathan's Home
  # Location required to calculate the time the sun rises and sets
  latitude: 37.5402
  longitude: -122.3041
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 8
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles

  customize: !include customize.yaml

    ### SWITCHES ###

    switch.aeotec_zw096_smart_switch_6_switch_11_0:
      friendly_name: Living Room Lamp
      icon: mdi:lightbulb-outline
    sensor.aeotec_zw096_smart_switch_6_energy_11_0:
      friendly_name: Living Room Lamp (Energy)
    sensor.aeotec_zw096_smart_switch_6_power_11_8:
      friendly_name: Living Room Lamp (Power)
    sensor.aeotec_zw096_smart_switch_6_previous_reading_11_1:
      hidden: true
    sensor.aeotec_zw096_smart_switch_6_current_11_20:
      friendly_name: Living Room Lamp (Current)
    sensor.aeotec_zw096_smart_switch_6_voltage_11_16:
      friendly_name: Living Room Lamp (Voltage)

    switch.aeotec_zw096_smart_switch_6_switch_12_0:
      friendly_name: Coffee Machine
      icon: mdi:lightbulb-outline
    sensor.aeotec_zw096_smart_switch_6_energy_12_0:
      friendly_name: Coffee Machine (Energy)
    sensor.aeotec_zw096_smart_switch_6_power_12_8:
      friendly_name: Coffee Machine (Power)
    sensor.aeotec_zw096_smart_switch_6_previous_reading_12_1:
      hidden: true
    sensor.aeotec_zw096_smart_switch_6_current_12_20:
      friendly_name: Coffee Machine (Current)
    sensor.aeotec_zw096_smart_switch_6_voltage_12_16:
      friendly_name: Coffee Machine (Voltage)

    switch.aeotec_zw096_smart_switch_6_switch_13_0:
      friendly_name: Bedroom Lamp
      icon: mdi:lightbulb-outline
    sensor.aeotec_zw096_smart_switch_6_energy_13_0:
      friendly_name: Bedroom Lamp (Energy)
    sensor.aeotec_zw096_smart_switch_6_power_13_8:
      friendly_name: Bedroom Lamp (Power)
    sensor.aeotec_zw096_smart_switch_6_previous_reading_13_1:
      hidden: true
    sensor.aeotec_zw096_smart_switch_6_current_13_20:
      friendly_name: Bedroom Lamp (Current)
    sensor.aeotec_zw096_smart_switch_6_voltage_13_16:
      friendly_name: Bedroom Lamp (Voltage)

    switch.aeotec_zw096_smart_switch_6_switch_14_0:
      friendly_name: Living Room TV
      icon: mdi:lightbulb-outline
    sensor.aeotec_zw096_smart_switch_6_energy_14_0:
      friendly_name: Living Room TV (Energy)
    sensor.aeotec_zw096_smart_switch_6_power_14_8:
      friendly_name: Living Room TV (Power)
    sensor.aeotec_zw096_smart_switch_6_previous_reading_14_1:
      hidden: true
    sensor.aeotec_zw096_smart_switch_6_current_14_20:
      friendly_name: Living Room TV (Current)
    sensor.aeotec_zw096_smart_switch_6_voltage_14_16:
      friendly_name: Living Room TV (Voltage)

    ### MULTI-SENSORS ###

    sensor.aeotec_zw100_multisensor_6_burglar_7_10:
      friendly_name: Balcony Motion
    sensor.aeotec_zw100_multisensor_6_luminance_7_3:
      friendly_name: Balcony Lumiance
    sensor.aeotec_zw100_multisensor_6_temperature_7_1:
      friendly_name: Balcony Temperature
    sensor.aeotec_zw100_multisensor_6_relative_humidity_7_5:
      friendly_name: Balcony Humidity
    sensor.aeotec_zw100_multisensor_6_ultraviolet_7_27:
      friendly_name: Balcony Ultraviolet
    binary_sensor.aeotec_zw100_multisensor_6_sensor_7_0:
      friendly_name: Balcony Presence
    sensor.aeotec_zw100_multisensor_6_alarm_type_7_0:
      friendly_name: Balcony Alarm Type
    sensor.aeotec_zw100_multisensor_6_alarm_level_7_1:
      friendly_name: Balcony Alarm Level
    sensor.aeotec_zw100_multisensor_6_sourcenodeid_7_2:
      friendly_name: Balcony Node ID

    sensor.aeotec_zw100_multisensor_6_burglar_2_10:
      friendly_name: Bedroom Motion
    sensor.aeotec_zw100_multisensor_6_luminance_2_3:
      friendly_name: Bedroom Lumiance
    sensor.aeotec_zw100_multisensor_6_temperature_2_1:
      friendly_name: Bedroom Temperature
    sensor.aeotec_zw100_multisensor_6_relative_humidity_2_5:
      friendly_name: Bedroom Humidity
    sensor.aeotec_zw100_multisensor_6_ultraviolet_2_27:
      friendly_name: Bedroom Ultraviolet
    binary_sensor.aeotec_zw100_multisensor_6_sensor_2_0:
      friendly_name: Bedroom Presence
    sensor.aeotec_zw100_multisensor_6_alarm_type_2_0:
      friendly_name: Bedroom Alarm Type
    sensor.aeotec_zw100_multisensor_6_alarm_level_2_1:
      friendly_name: Bedroom Alarm Level
    sensor.aeotec_zw100_multisensor_6_sourcenodeid_2_2:
      friendly_name: Bedroom Node ID

    sensor.aeotec_zw100_multisensor_6_burglar_9_10:
      friendly_name: Living Room Motion
    sensor.aeotec_zw100_multisensor_6_luminance_9_3:
      friendly_name: Living Room Lumiance
    sensor.aeotec_zw100_multisensor_6_temperature_9_1:
      friendly_name: Living Room Temperature
    sensor.aeotec_zw100_multisensor_6_relative_humidity_9_5:
      friendly_name: Living Room Humidity
    sensor.aeotec_zw100_multisensor_6_ultraviolet_9_27:
      friendly_name: Living Room Ultraviolet
    binary_sensor.aeotec_zw100_multisensor_6_sensor_9_0:
      friendly_name: Living Room Presence
    sensor.aeotec_zw100_multisensor_6_alarm_type_9_0:
      friendly_name: Living Room Alarm Type
    sensor.aeotec_zw100_multisensor_6_alarm_level_9_1:
      friendly_name: Living Room Alarm Level
    sensor.aeotec_zw100_multisensor_6_sourcenodeid_9_2:
      friendly_name: Living Room Node ID

    sensor.aeotec_zw100_multisensor_6_burglar_6_10:
      friendly_name: Bathroom Motion
    sensor.aeotec_zw100_multisensor_6_luminance_6_3:
      friendly_name: Bathroom Lumiance
    sensor.aeotec_zw100_multisensor_6_temperature_6_1:
      friendly_name: Bathroom Temperature
    sensor.aeotec_zw100_multisensor_6_relative_humidity_6_5:
      friendly_name: Bathroom Humidity
    sensor.aeotec_zw100_multisensor_6_ultraviolet_6_27:
      friendly_name: Bathroom Ultraviolet
    binary_sensor.aeotec_zw100_multisensor_6_sensor_6_0:
      friendly_name: Bathroom Presence
    sensor.aeotec_zw100_multisensor_6_alarm_type_6_0:
      friendly_name: Bathroom Alarm Type
    sensor.aeotec_zw100_multisensor_6_alarm_level_6_1:
      friendly_name: Bathroom Alarm Level
    sensor.aeotec_zw100_multisensor_6_sourcenodeid_6_2:
      friendly_name: Bathroom Node ID

    sensor.aeotec_zw100_multisensor_6_burglar_10_10:
      friendly_name: Kitchen Motion
    sensor.aeotec_zw100_multisensor_6_luminance_10_3:
      friendly_name: Kitchen Lumiance
    sensor.aeotec_zw100_multisensor_6_temperature_10_1:
      friendly_name: Kitchen Temperature
    sensor.aeotec_zw100_multisensor_6_relative_humidity_10_5:
      friendly_name: Kicthen Humidity
    sensor.aeotec_zw100_multisensor_6_ultraviolet_10_27:
      friendly_name: Kitchen Ultraviolet
    binary_sensor.aeotec_zw100_multisensor_6_sensor_10_0:
      friendly_name: Kitchen Presence
    sensor.aeotec_zw100_multisensor_6_alarm_type_10_0:
      friendly_name: Kitchen Alarm Type
    sensor.aeotec_zw100_multisensor_6_alarm_level_10_1:
      friendly_name: Kitchen Alarm Level
    sensor.aeotec_zw100_multisensor_6_sourcenodeid_10_2:
      friendly_name: Kitchen Node ID

zone:
  name: My House
  latitude: 37.5402
  longitude: -122.3041
  icon: mdi:home
  radius: 500


# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Homma ML
#homma_ml:

# Weather Prediction
sensor:
  platform: yr

# Text to speech
tts:
  platform: google

mqtt:
  broker: 10.0.0.100
  port: 1883
  client_id: home-assistant-1
  username: jwills
  password: cantgetin789520

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config

group:

  living_room:
    name: Living Room
    view: no
    entities:
      - binary_sensor.aeotec_zw100_multisensor_6_sensor_9_0
      - sensor.aeotec_zw100_multisensor_6_alarm_level_9_1
      - sensor.aeotec_zw100_multisensor_6_alarm_type_9_0 
      - sensor.aeotec_zw100_multisensor_6_burglar_9_10
      - sensor.aeotec_zw100_multisensor_6_luminance_9_3
      - sensor.aeotec_zw100_multisensor_6_relative_humidity_9_5
      - sensor.aeotec_zw100_multisensor_6_sourcenodeid_9_2
      - sensor.aeotec_zw100_multisensor_6_temperature_9_1
      - sensor.aeotec_zw100_multisensor_6_ultraviolet_9_27

  kitchen:
    name: Kitchen
    view: no
    entities:
      - binary_sensor.aeotec_zw100_multisensor_6_sensor_10_0
      - sensor.aeotec_zw100_multisensor_6_alarm_level_10_1
      - sensor.aeotec_zw100_multisensor_6_alarm_type_10_0 
      - sensor.aeotec_zw100_multisensor_6_burglar_10_10
      - sensor.aeotec_zw100_multisensor_6_luminance_10_3
      - sensor.aeotec_zw100_multisensor_6_relative_humidity_10_5
      - sensor.aeotec_zw100_multisensor_6_sourcenodeid_10_2
      - sensor.aeotec_zw100_multisensor_6_temperature_10_1
      - sensor.aeotec_zw100_multisensor_6_ultraviolet_10_27

  bedroom:
    name: Bedroom
    view: no
    entities:
      - binary_sensor.aeotec_zw100_multisensor_6_sensor_2_0
      - sensor.aeotec_zw100_multisensor_6_alarm_level_2_1
      - sensor.aeotec_zw100_multisensor_6_alarm_type_2_0
      - sensor.aeotec_zw100_multisensor_6_burglar_2_10
      - sensor.aeotec_zw100_multisensor_6_luminance_2_3
      - sensor.aeotec_zw100_multisensor_6_relative_humidity_2_5
      - sensor.aeotec_zw100_multisensor_6_sourcenodeid_2_2
      - sensor.aeotec_zw100_multisensor_6_temperature_2_1
      - sensor.aeotec_zw100_multisensor_6_ultraviolet_2_27

  bathroom:
    name: Bathroom
    view: no
    entities:
      - binary_sensor.aeotec_zw100_multisensor_6_sensor_6_0
      - sensor.aeotec_zw100_multisensor_6_alarm_level_6_1
      - sensor.aeotec_zw100_multisensor_6_alarm_type_6_0 
      - sensor.aeotec_zw100_multisensor_6_burglar_6_10
      - sensor.aeotec_zw100_multisensor_6_luminance_6_3
      - sensor.aeotec_zw100_multisensor_6_relative_humidity_6_5
      - sensor.aeotec_zw100_multisensor_6_sourcenodeid_6_2
      - sensor.aeotec_zw100_multisensor_6_temperature_6_1
      - sensor.aeotec_zw100_multisensor_6_ultraviolet_6_27

  balcony:
    name: Balcony
    view: no
    entities:
      - binary_sensor.aeotec_zw100_multisensor_6_sensor_7_0
      - sensor.aeotec_zw100_multisensor_6_alarm_level_7_1
      - sensor.aeotec_zw100_multisensor_6_alarm_type_7_0 
      - sensor.aeotec_zw100_multisensor_6_burglar_7_10
      - sensor.aeotec_zw100_multisensor_6_luminance_7_3
      - sensor.aeotec_zw100_multisensor_6_relative_humidity_7_5
      - sensor.aeotec_zw100_multisensor_6_sourcenodeid_7_2
      - sensor.aeotec_zw100_multisensor_6_temperature_7_1
      - sensor.aeotec_zw100_multisensor_6_ultraviolet_7_27
 
  motion:
    name: Motion
    entities:
      - binary_sensor.aeotec_zw100_multisensor_6_sensor_9_0
      - binary_sensor.aeotec_zw100_multisensor_6_sensor_10_0
      - binary_sensor.aeotec_zw100_multisensor_6_sensor_2_0 
      - binary_sensor.aeotec_zw100_multisensor_6_sensor_6_0
      - binary_sensor.aeotec_zw100_multisensor_6_sensor_7_0

  living_room_lamp:
    name: Living Room Lamp
    entities:
      - switch.aeotec_zw096_smart_switch_6_switch_11_0
      - sensor.aeotec_zw096_smart_switch_6_energy_11_0
      - sensor.aeotec_zw096_smart_switch_6_power_11_8
      - sensor.aeotec_zw096_smart_switch_6_previous_reading_11_1
      - sensor.aeotec_zw096_smart_switch_6_current_11_20
      - sensor.aeotec_zw096_smart_switch_6_voltage_11_16

  living_room_tv:
    name: Living Room TV
    entities:
      - switch.aeotec_zw096_smart_switch_6_switch_14_0
      - sensor.aeotec_zw096_smart_switch_6_energy_14_0
      - sensor.aeotec_zw096_smart_switch_6_power_14_8
      - sensor.aeotec_zw096_smart_switch_6_previous_reading_14_1
      - sensor.aeotec_zw096_smart_switch_6_current_14_20
      - sensor.aeotec_zw096_smart_switch_6_voltage_14_16

  kitche_coffee_machine:
    name: Kitchen Coffee Machine
    entities:
      - switch.aeotec_zw096_smart_switch_6_switch_12_0
      - sensor.aeotec_zw096_smart_switch_6_energy_12_0
      - sensor.aeotec_zw096_smart_switch_6_power_12_8
      - sensor.aeotec_zw096_smart_switch_6_previous_reading_12_1
      - sensor.aeotec_zw096_smart_switch_6_current_12_20
      - sensor.aeotec_zw096_smart_switch_6_voltage_12_16

  bedroom_lamp:
    name: Bedroom Lamp
    entities:
      - switch.aeotec_zw096_smart_switch_6_switch_13_0
      - sensor.aeotec_zw096_smart_switch_6_energy_13_0
      - sensor.aeotec_zw096_smart_switch_6_power_13_8
      - sensor.aeotec_zw096_smart_switch_6_previous_reading_13_1
      - sensor.aeotec_zw096_smart_switch_6_current_13_20
      - sensor.aeotec_zw096_smart_switch_6_voltage_13_16

  all_lamps:
    name: All Lamps
    entities: 
      - group.bedroom_lamp
      - group.living_room_lamp

automation:
  alias: Turn on light when sun sets
  hide_entity: False
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  condition:
    condition: state
    entity_id: group.all_devices
    state: 'home'
  action:
    service: light.turn_on
