homeassistant:
  # Name of the location where Home Assistant is running
  name: Jonathan's Home
  # Location required to calculate the time the sun rises and sets
  latitude: 37.542874
  longitude: -122.283156
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 8
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

zone:
  name: Jonathan's Home
  latitude: 37.542874
  longitude: -122.283156
  icon: mdi:home
  radius: 300

# Show links to resources in log and frontend
#introduction:

logger:
    default: error
    homeassistant.components.homma_control: debug
    custom_components.homma_control: debug

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Homma ML
#homma_ml:

# Weather Prediction
sensor:
  platform: yr

# Text to speech
tts:
  platform: google

homma_control:
  home_id: 88f332a5-61df-4ee5-a82d-06a362c681d7
  session_token: qZOM_m7BIP7-d8nxWmbj

# mqtt:
#   broker: 10.0.0.100
#   port: 1883
#   client_id: ome-assistant-jwills
#   username: jwills
#   password: cantgetin789520

mqtt:
  broker: mqtt-stage.homma.io
  port: 1883
  client_id: home-assistant-jwills
  username: homma
  password: WJTRTcEEvrJNgLKWgUK8jLzE7WQyNV

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config

# automation: !include automation.yaml
group: !include groups.yaml
